### ISSUE TITLE
Update cookiecutter sample app for the latest aws-powertools-java version(1.14.0)

### ISSUE THREAD

**Issue by machafer** [awslabs/aws-lambda-powertools-java#1049]
Cookiecutter sample app for aws-sam-powertools-java is using Java 1.12.0 and outdated libs for Log4j &, post-compile-weaving  & maven-shade-plugin

**What were you trying to accomplish?**
I was trying to deploy a powertools sample application using 
[cookiecutter-aws-sam-powertools-java](https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java)

## Expected Behavior

Would be nice to see a sample app using the latest powertools app version. 

## Possible Solution

1/Rollout pending lib upgrades. Here is the proposal PR to fix this.
https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java/pull/597. 2/ Close existent opened PRs - There are over 30+ opened.  

## Steps to Reproduce (for bugs)

1. run 'sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java'
2.
3.
4.

## Environment

* **Powertools version used**:  
* **Packaging format (Layers, Maven/Gradle)**:
* **AWS Lambda function runtime:**
* **Debugging logs**

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-java/#debug-mode)**

```text
# paste logs here
```

**Comment by kozub** [comment]
I think that this issue is more related to maintenance work for [cookiecutter-aws-sam-powertools-java](https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java) project and it should be moved to its issues list. 

It looks that the cookiecutter-aws-sam-powertools-java project is abandoned so we might consider taking care of it.  
When the cookiecutter-aws-sam-powertools-java will be up to date we might mention it in the examples section of README.

**Comment by machafer** [comment]
Hey @kozub, I do agree. Somehow it got mapped to bug. Here is the proposal PR to fix this. 
https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java/pull/597 
Can you review it please? Thanks!

**Comment by machafer** [comment]
Implemented [here](https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java/pull/597)
