### ISSUE TITLE
Set default values for tracing utilty parameters

### ISSUE THREAD

**Issue by RobertoC27** [awslabs/aws-lambda-powertools-java#231]
**Is your feature request related to a problem? Please describe.**
Changing the default captureResult param for the tracing utility to "false" would make my life easier, given that most of my methods require having it turned off because it causes errors while interacting with other services.

**Describe the solution you'd like**
It would be nice to be able to set the captureResult property for the tracing annotation to false and let all methods called inherit that default instead of having to put capture=false on every single annotation

**Describe alternatives you've considered**
right now I override the params on every annotation

**Additional context**
I'm working with a library that fails when tracing's capture response is true

**Comment by heitorlessa** [comment]
Would an environment variable help here?

That way you wouldn't change your code, and yet override the default -- it's something we've been thinking for the Python Powertools, at least.

For our own learning, could you share more on what services you're working with that this breaks? 

We know S3 is one of them

**Comment by RobertoC27** [comment]
Yes, env vars make sense for this! I'm working with Cloudhsm, using the JCE. Curious that you mention S3, since that has not given us any issues with capture response.

**Comment by pankajagrawal16** [comment]
Agreed, the environment variable will probably be best here following how other utilities behave as well.

**Comment by pankajagrawal16** [comment]
I looked a bit into the implementation aspect of this. Few immediate thoughts, Since Java annotation won't allow `Boolean` as an attribute type, we might have to take the annotation way. In order to distinguish if its a default value or user has specified it before honoring any specific environment variable, we need something which is not primitive like true/false.

Practically, that would mean something like:

<pre>
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface PowertoolsTracing {
    String namespace() default "";
    <b>@Deprecated</b>
    boolean captureResponse() default true;
    <b>@Deprecated</b>
    boolean captureError() default true;
    <b>CaptureMode mode() default CaptureMode.ENVIRONMENT_VAR;</b>
}
</pre>

<pre>
public enum CaptureMode {
    RESPONSE,
    ERROR,
    RESPONSE_AND_ERROR,
    ENVIRONMENT_VAR
}
</pre>

The default value of mode can be ENVIRONMENT_VAR and which can in turn default to true if no env variable is specified. 

**Pros:**

- Requested feature can be supported in a clean way and also gives possibility of adding other modes if thats needed ever(right now cannot think of any though)

**Cons:**

- Will be a breaking change for users **if they are overriding the default values today** once we remove the deprecated attributes.

Unless I am missing something completely obvious and this can be solved in simpler way, Will be interesting to hear thoughts from others too.

**Comment by RobertoC27** [comment]
you are right, for us this would be a breaking change. no doubt but in the end it leads to a cleaner code. 
Am i understanding this is how it would be or am i wrong?
```java
// Current way of handling things
@Tracing (captureResponse=false)
public void someMethod(int param, ...)

@Tracing (captureResponse=false)
public void noErrorCapture(int param, ...)

@Tracing (captureError=false)
public void anotherMethod(int param, ...)

@Tracing
public void extraMethod(int param, ...)

// Proposed way
@Tracing
@CaptureMode(mode="ENVIRONMENT_VAR")
public void someMethod(int param, ...)

@CaptureMode(mode="ENVIRONMENT_VAR")
public void noErrorCapture(int param, ...)

@Tracing 
@CaptureMode(mode="RESPONSE")
public void anotherMethod(int param, ...)

@Tracing 
@CaptureMode(mode="RESPONSE_AND_ERROR") //this would be optional since default mode is capture both, right?
public void extraMethod(int param, ...)
```

**Comment by pankajagrawal16** [comment]
Yeah like this, except that the `mode` value is an enum and strongly typed instead of a String.

Also, the default value will be `ENVIRONMENT_VAR ` which will default capture response and error to `true` if no environment variable specified. This practically means, if users today are using the default configuration, they won't need to change anything. 

If users want to change the default behavior, they can just override the 2 new environment variable to whatever value they want. 

If users want to override behavior for some of the users only, then they can choose any one of the supported modes. 

Hope this makes sense? @RobertoC27

**Comment by RobertoC27** [comment]
> If users want to change the default behavior, they can just override the 2 new environment variable to whatever value they want.

one final question, is there going to be 1 env var per behavior?

**Comment by pankajagrawal16** [comment]
Yeah, At least that's how I have thought about it so far [here](https://github.com/awslabs/aws-lambda-powertools-java/compare/master...tracing-caputre-modes#diff-26c6b1069f1cea5fed77ab5ee80ffa916fadee0889b6c99a53ee2122738ec8c3R35)

**Comment by RobertoC27** [comment]
makes sense, since combining them would make more complex overriding them down the line.

**Comment by pankajagrawal16** [comment]
Hi @RobertoC27 , This is now available in [v1.2.0](https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.2.0). Do try out and let us know in case of any feedback/issues.

**Comment by RobertoC27** [comment]
Hey @pankajagrawal16 
We finally got to migrate our lambdas to this new version and its is working with no issues so far, thanks!

**Comment by pankajagrawal16** [comment]
> Hey @pankajagrawal16
> We finally got to migrate our lambdas to this new version and its is working with no issues so far, thanks!

Hey @RobertoC27, Great to hear!
