### ISSUE TITLE
Feature request: support large payload messages received from SNS

### ISSUE THREAD

**Issue by qtdzz** [awslabs/aws-lambda-powertools-java#603]
**Is your feature request related to a problem? Please describe.**
Currently, `@SqsLargeMessage` only supports large messages which are sent directly from SQSExtendedClient, i.e: `SQSExtendedClient -> SQS -> Lambda`.

A common use case I've seen is subscribing the SQS to an external SNS topic where the topic could have large payload message as well, i.e. `SNSExtendedClient -> SNS -> SQS -> Lambda`.

Right now, the expected SQSEvent is:
```
{
    "records": [
        {
            "body": "[\"software.amazon.payloadoffloading.PayloadS3Pointer\",{\"s3BucketName\":\"some-bucket\",\"s3Key\":\"some-key\"}]",
            ...
        }

    ]
}
```
In the SNS case, the body would be a serialized string of [SNSEvent.SNS class](https://github.com/aws/aws-lambda-java-libs/blob/311f97cc47b414633c62ee96d9df3e8404e14d69/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SNSEvent.java#L162). After deserializing it, [SNSEvent.SNS#getMessage()](https://github.com/aws/aws-lambda-java-libs/blob/311f97cc47b414633c62ee96d9df3e8404e14d69/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SNSEvent.java#L172) would return a PayloadS3Pointer as the current case.

**Describe the solution you'd like**

We could either have a flag for the current annotation or another annotation to essentially the string message of the SNS event before checking if it's a large message or not. We will need to reconstruct the SNSEvent.SNS as the body of the records though.

**Comment by msailes** [comment]
Hi @qtdzz,

I think this is well understood issue and it can be worked on. Would you be interested in contributing? Either with code, testing or documentation?

**Comment by qtdzz** [comment]
Hi @msailes, unfortunately I don't have time and interest to work on this anymore.

**Comment by scottgerring** [comment]
@msailes I can pick this up !

**Comment by mriccia** [comment]
happy to pick this up, if you aren't planning to look at it in the next month @scottgerring

**Comment by mriccia** [comment]
hi @qtdzz,
I looked into the issue and I can see that the `@SqsLargeMessage` annotation does not unwrap the message from S3, when the message is published from SNS to SQS.
This happens because SNS wrappes the message with additional metadata.

Do you require the additional SNS metadata from the message? 
If so, may I ask what do you use the SNS metadata for?

In case you don't require the additional metadata, you can modify your SNS->SQS subscription to only send the original raw message without metadata.
This option is called [raw message delivery](https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html#raw-message-examples). You can set this flag on the SNS Subscription, if you use CloudFormation or SAM, set the `RawMessageDelivery: true` on the `AWS::SNS::Subscription` see [the docs here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-rawmessagedelivery)

**Comment by qtdzz** [comment]
Thank you @mriccia for taking a look at the issue.

Unfortunately, I don't remember exactly the use case of SNS metada (and I don't work on the project anymore), probably I just didn't know I could use raw message delivery to use this feature.

Please feel free to close the issue :) thank you!

**Comment by mriccia** [comment]
Thank you @qtdzz for getting back to me, closing the issue

**Comment by jeromevdl** [comment]
See #1259
